projects:
  app:
    includes: ['**/*.graphql']
    schemaPath: src/graphql/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    includes: ['**/*.graphql']
    schemaPath: src/graphql/generated/prisma.graphql
    extensions:
      prisma: src/prisma/prisma.yml
